### ISSUE TITLE
Use XMLHttpRequest "constants" instead of int

### ISSUE THREAD

**Issue by franz-josef-kaiser** [score-framework/js.ajax#1]
Inside [`score.ajax.callback()`](https://github.com/score-framework/js.ajax/blob/823ffee9b4ad6b648bd2637a14a2cbc1afc9dc6c/ajax.js#L63), the `request`s state gets questioned. As I am currently debugging an uncatched error, I noticed that integers are in use. Those could – for the sake of understand- and readability – get changed to the objects variables representing the different states:

```
request.readyState === XMLHttpRequest.DONE
```

It might be useful to have an `else` clause to catch other states in case the request did fail internally and proceeds to the handler without actually being in [`DONE`](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/readyState) state. In any other case, the `if` itself is redundant and could be left off.

_[Related MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/onreadystatechange)._

**Comment by soulmerge** [comment]
Sounds reasonable, implemented the change as suggested.
